baseURL = "https://sparnebrau.nl/"
defaultcontentlanguage = "nl"
languageCode = "nl-nl"
title = "Spärne Bräu"
theme = "hugo-theme-bleak"
enableRobotsTXT = true

[params]
  # Warning Keys are case sensitives
  Subtitle = "A Homebrew Blog"
  cover = "/images/hops.jpg"

  [params.author]
    firstName = "Arnoud"
    lastName = "de Jonge"
    userName = "arnoud"
    website = "https://sparnebrau.nl"
    twitter = "@noudsch"
